---
- name: build a front Service
  hosts: test_vagrant
  sudo: true
  remote_user: vagrant
  tasks:
    - name: Copy front package
      copy:
        src: ../client_build.tar
        dest: /home/meet/
    - name: tar xvf front package
      command: tar xvf /home/meet/client_build.tar
    - name: Copy project jar
      copy:
        src: ./deploy_jar.sh
        dest: /var
    - name: run front package
      command: sh /var/deploy_front.sh